name: Run Selenium Scraper

on:
  schedule:
    - cron: '0 1 * * *' # Exécuter tous les jours à 1h du matin UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape_wind_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install Chrome and Chromedriver manually
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable unzip curl jq

        # Récupérer la version exacte de Chrome
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')

        # Récupérer la version correspondante de Chromedriver
        DRIVER_URL=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | \
          jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')

        if [ -z "$DRIVER_URL" ]; then
          echo "No matching Chromedriver version found!"
          exit 1
        fi

        # Télécharger et installer Chromedriver
        wget -N "$DRIVER_URL" -O chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver





    - name: Run Selenium script
      run: python prt.py

    - name: Commit and push CSV
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add wind_data1.csv
        git commit -m 'Mise à jour des données de vent' || echo 'Aucune modification'
        git push