name: Run Selenium Scraper

on:
  schedule:
    - cron: '40 18 * * *' # Exécuter toutes les 6 heures
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape_wind_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install Chrome and Chromedriver manually
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable unzip
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget -N "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver



    - name: Run Selenium script
      run: python prt.py

    - name: Commit and push CSV
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add wind_data1.csv
        git commit -m 'Mise à jour des données de vent' || echo 'Aucune modification'
        git push